### ISSUE TITLE
Flag unable to be grabbed by either team

### ISSUE THREAD

**Issue by jszobody** [wight-airmash/ab-server#16] opened 2019-08-31 03:27 UTC
I just joined CTF, and found this:

![2019-08-30_23-23-25](https://user-images.githubusercontent.com/203749/64058720-42962f00-cb7d-11e9-9f68-76dde07ff3ea.png)

The red flag is in blue base, and none of the blue bots are able to take it. I tried repeatedly flying over the flag and nothing happened.

I switched to red and flew over, still couldn't do anything with the flag. Flying over it did not recap.

I have no idea how it got into this state.

**Comment by wight-airmash** [comment] 2019-08-31 07:53
Duplicate of #15

**Closed by wight-airmash** 2019-08-31 07:53 UTC
Labels: bug
